---
- name: test storage_filesystems
  ansible.builtin.assert:
    that:
      - filesystem.name is defined
    quiet: yes

- name: create filesystems
  community.general.filesystem:
    dev: "{{ filesystem.name }}"
    fstype: "{{ filesystem.filesystem | default(storage_default_fstype) }}"
